<?php

namespace Proxies\__CG__\Mytrip\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Story extends \Mytrip\AdminBundle\Entity\Story implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'storyId', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'name', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'url', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'createdDate', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'status', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'hostal', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'destination', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'topStory');
        }

        return array('__isInitialized__', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'storyId', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'name', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'url', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'createdDate', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'status', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'hostal', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'destination', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\Story' . "\0" . 'topStory');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Story $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getStoryId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getStoryId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStoryId', array());

        return parent::getStoryId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate($createdDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', array($createdDate));

        return parent::setCreatedDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', array());

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setHostal(\Mytrip\AdminBundle\Entity\Hostal $hostal = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHostal', array($hostal));

        return parent::setHostal($hostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getHostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHostal', array());

        return parent::getHostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestination(\Mytrip\AdminBundle\Entity\Destination $destination = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestination', array($destination));

        return parent::setDestination($destination);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestination()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestination', array());

        return parent::getDestination();
    }

    /**
     * {@inheritDoc}
     */
    public function setTopStory($topStory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTopStory', array($topStory));

        return parent::setTopStory($topStory);
    }

    /**
     * {@inheritDoc}
     */
    public function getTopStory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTopStory', array());

        return parent::getTopStory();
    }

}
