<?php

namespace Proxies\__CG__\Mytrip\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ApiInfo extends \Mytrip\AdminBundle\Entity\ApiInfo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\ApiInfo' . "\0" . 'apiInfoId', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\ApiInfo' . "\0" . 'metaKey', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\ApiInfo' . "\0" . 'metaValue', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\ApiInfo' . "\0" . 'api');
        }

        return array('__isInitialized__', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\ApiInfo' . "\0" . 'apiInfoId', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\ApiInfo' . "\0" . 'metaKey', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\ApiInfo' . "\0" . 'metaValue', '' . "\0" . 'Mytrip\\AdminBundle\\Entity\\ApiInfo' . "\0" . 'api');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ApiInfo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getApiInfoId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getApiInfoId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiInfoId', array());

        return parent::getApiInfoId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaKey($metaKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaKey', array($metaKey));

        return parent::setMetaKey($metaKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaKey', array());

        return parent::getMetaKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaValue($metaValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaValue', array($metaValue));

        return parent::setMetaValue($metaValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaValue', array());

        return parent::getMetaValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setApi(\Mytrip\AdminBundle\Entity\ApiGateway $api = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApi', array($api));

        return parent::setApi($api);
    }

    /**
     * {@inheritDoc}
     */
    public function getApi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApi', array());

        return parent::getApi();
    }

}
