Mytrip\AdminBundle\Entity\Admin:
    type: entity
    table: admin
    id:
        adminId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: admin_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        username:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        status:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: Active
        createdDate:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: created_date
        modifyDate:
            type: datetime
            nullable: false
            comment: ''
            column: modify_date
        cmcode:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        mobile:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
