Mytrip\AdminBundle\Entity\ApiGatway:
    type: entity
    table: api_gatway
    id:
        apiId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: api_id
            generator:
                strategy: IDENTITY
    fields:
        gatway:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        status:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: Active
    lifecycleCallbacks: {  }
