Mytrip\AdminBundle\Entity\Country:
    type: entity
    table: country
    id:
        cid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        country:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        isocountry:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
