Mytrip\AdminBundle\Entity\Feature:
    type: entity
    table: feature
    id:
        featureId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: feature_id
            generator:
                strategy: IDENTITY
    fields:
        feature:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        icon:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
        createdDate:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: created_date
    lifecycleCallbacks: {  }
