Mytrip\AdminBundle\Entity\HostalImage:
    type: entity
    table: hostal_image
    indexes:
        hostal_id:
            columns:
                - hostal_id
    id:
        hostalImageId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: hostal_image_id
            generator:
                strategy: IDENTITY
    fields:
        image:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
        createdDate:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: created_date
    manyToOne:
        hostal:
            targetEntity: Hostal
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                hostal_id:
                    referencedColumnName: hostal_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
