Mytrip\AdminBundle\Entity\HostalFeature:
    type: entity
    table: hostal_feature
    indexes:
        hostal_id:
            columns:
                - hostal_id
        feature_id:
            columns:
                - feature_id
    id:
        hostalFeatureId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: hostal_feature_id
            generator:
                strategy: IDENTITY
    fields:
        createdDate:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: created_date
    manyToOne:
        hostal:
            targetEntity: Hostal
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                hostal_id:
                    referencedColumnName: hostal_id
            orphanRemoval: false
        feature:
            targetEntity: Feature
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                feature_id:
                    referencedColumnName: feature_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
