Mytrip\AdminBundle\Entity\Settings:
    type: entity
    table: settings
    id:
        settingId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: setting_id
            generator:
                strategy: IDENTITY
    fields:
        reservationCharge:
            type: float
            nullable: false
            precision: 8
            scale: 2
            comment: percentage
            column: reservation_charge
        bookingPercentage:
            type: float
            nullable: false
            precision: 8
            scale: 2
            comment: percentage
            column: booking_percentage
        bookingConfirmationDays:
            type: integer
            nullable: false
            unsigned: false
            comment: days
            column: booking_confirmation_days
    lifecycleCallbacks: {  }
