Mytrip\AdminBundle\Entity\SocialLink:
    type: entity
    table: social_link
    id:
        socialLinkId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: social_link_id
            generator:
                strategy: IDENTITY
    fields:
        site:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        link:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        createdDate:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: created_date
    lifecycleCallbacks: {  }
