Mytrip\AdminBundle\Entity\StoryImage:
    type: entity
    table: story_image
    indexes:
        story_id:
            columns:
                - story_id
    id:
        storyImageId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: story_image_id
            generator:
                strategy: IDENTITY
    fields:
        image:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
        createdDate:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: created_date
    manyToOne:
        story:
            targetEntity: Story
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                story_id:
                    referencedColumnName: story_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
