Mytrip\AdminBundle\Entity\UserSocialLink:
    type: entity
    table: user_social_link
    indexes:
        user_id:
            columns:
                - user_id
    id:
        userSocialLinkId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: user_social_link_id
            generator:
                strategy: IDENTITY
    fields:
        socialLink:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: social_link
        id:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        image:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        createdDate:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: created_date
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: user_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
