imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: payum.yml }
    #- { resource: service.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig','php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    

# Twig Configuration
twig:
    paths:
        %kernel.root_dir%/../vendor/Payum/Core/Resources/views: PayumCore
       # %kernel.root_dir%/../vendor/Payum/Klarna/Checkout/Resources/views: PayumKlarnaCheckout
       # %kernel.root_dir%/../vendor/Payum/Stripe/Resources/views: PayumStripe

    
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
             enum: string
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"            
        entity_managers:
            default:
                mappings:
                    payum:
                        is_bundle: false
                        type: xml
                        dir: %kernel.root_dir%/../vendor/Payum/Core/Bridge/Doctrine/Resources/mapping

                        # set this dir instead if you use `payum/payum` library
                        #dir: %kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Bridge/Doctrine/Resources/mapping

                        prefix: Payum\Core\Model
                auto_mapping: true
       # auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    #host:      "%mailer_host%"
    #username:  "%mailer_user%"
    #password:  "%mailer_password%"
    #spool:     { type: memory }
# KNP paginator Configuration
knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

jms_payment_core:
    secret:                                               %secret%

jms_payment_paypal:
    username:                                             %paypal.express_checkout.username%
    password:                                             %paypal.express_checkout.password%
    signature:                                            %paypal.express_checkout.signature%
    debug:                                                true


#Date format
mytrip_admin:
    helper:
        date: {default_format: %default_format%,detailed_format: %detailed_format%}
        amazon: {awsAccessKey: %awsAccessKey%,awsSecretKey: %awsSecretKey%,bucket: %amazon_bucket%,url: %amazon_bucket_url%}
        beanstream: {beanstream_merchant_id_usd: %beanstream.merchant_id_usd%,beanstream_username_usd: %beanstream.username_usd%,beanstream_password_usd: %beanstream.password_usd%,beanstream_merchant_id_cad: %beanstream.merchant_id_cad%,beanstream_username_cad: %beanstream.username_cad%,beanstream_password_cad: %beanstream.password_cad%}
        facebook: {apikey: %facebook_apikey%,apisecretkey: %facebook_apisecretkey%}
        twitter: {apikey: %twitter_apikey%,apisecretkey: %twitter_apisecretkey%}
        google: {apikey: %google_apikey%,apisecretkey: %google_apisecretkey%,developerkey: %google_developerkey%,product: %google_product_name%}
        recaptcha: {publickey: %recaptcha_publickey%,privatekey: %recaptcha_priavatekey%}
        sms: {smsusername: %smsusername%,smspassword: %smspassword%}
        globalone: {terminalid: %terminalid%,secret: %secret%,multicurrency: %multicurrency%,testaccount: %testaccount%}

