payum:
    storages:
        Mytrip\PaymentBundle\Entity\PaymentDetails:
            payment:
                all: true
            doctrine: orm

        Mytrip\PaymentBundle\Document\PaymentDetails:
            payment:
                contexts:
                    - paypal_express_checkout_and_doctrine_orm
            doctrine: orm

        Mytrip\PaymentBundle\Entity\AgreementDetails:
            payment:
                contexts:
                    - paypal_express_checkout_recurring_payment_and_doctrine_orm
            doctrine: orm

        Mytrip\PaymentBundle\Entity\RecurringPaymentDetails:
            payment:
                contexts:
                    - paypal_express_checkout_recurring_payment_and_doctrine_orm
            doctrine: orm

        Mytrip\PaymentBundle\Model\AgreementDetails:
            payment:
                contexts:
                    - payex_agreement
            filesystem:
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id

        #Mytrip\OtherExamplesBundle\Model\Cart:
            #payment:
                #contexts:
                    #- paypal_express_checkout_plus_cart
                    #- authorize_net_plus_cart
            #filesystem:
                #storage_dir: %kernel.root_dir%/Resources/payments
                #id_property: id

        JMS\Payment\CoreBundle\Entity\Payment:
            payment:
                contexts:
                    - paypal_express_checkout_via_jms_plugin
            doctrine: orm

        Mytrip\PaymentBundle\Model\PaymentDetails:
            filesystem:
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id

    security:
        token_storage:
            Mytrip\PaymentBundle\Entity\PaymentSecurityToken:
                doctrine: orm

    contexts:
        paypal_express_checkout_and_doctrine_orm:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox: false

        stripe_js:
            stripe_js:
                publishable_key: %stripe.publishable_key%
                secret_key: %stripe.secret_key%

        stripe_checkout:
            stripe_checkout:
                publishable_key: %stripe.publishable_key%
                secret_key: %stripe.secret_key%

        #skrill:
           # skrill:
               # email: %skrill.email%
               # password: %skrill.password%

       # stripe_via_omnipay:
           # omnipay:
             #   type: Stripe
             #   options:
              #      apiKey:  %stripe.secret_key%
               #     testMode: true

        