parameters:
#    mytrip_admin.example.class: Mytrip\AdminBundle\Example

services:
#    mytrip_admin.example:
#        class: %mytrip_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    mytrip_admin.helper.date:
        class:        Mytrip\AdminBundle\Helper\DateHelper
        arguments:    [%mytrip_admin.helper.date%]
    mytrip_admin.helper.amazon:
        class:        Mytrip\AdminBundle\Helper\AmazonHelper
        arguments:    [%mytrip_admin.helper.amazon%]
    mytrip_admin.helper.beanstream:
        class:        Mytrip\AdminBundle\Helper\BeanstreamHelper
        arguments:    [%mytrip_admin.helper.beanstream%]
    mytrip_admin.helper.facebook:
        class:        Mytrip\AdminBundle\Helper\FacebookHelper
        arguments:    [%mytrip_admin.helper.facebook%]
    mytrip_admin.helper.twitter:
        class:        Mytrip\AdminBundle\Helper\TwitterHelper
        arguments:    [%mytrip_admin.helper.twitter%]
    mytrip_admin.helper.google:
        class:        Mytrip\AdminBundle\Helper\GoogleHelper
        arguments:    [%mytrip_admin.helper.google%]
    mytrip_admin.helper.recaptcha:
        class:        Mytrip\AdminBundle\Helper\RecaptchaHelper
        arguments:    [%mytrip_admin.helper.recaptcha%]
    mytrip_admin.helper.sms:
        class:        Mytrip\AdminBundle\Helper\SmsHelper
        arguments:    [%mytrip_admin.helper.sms%]
    mytrip_admin.helper.globalone:
        class:        Mytrip\AdminBundle\Helper\GlobaloneHelper
        arguments:    [%mytrip_admin.helper.globalone%]