parameters:
#    mytrip_user.example.class: Mytrip\UserBundle\Example

services:
#    mytrip_user.example:
#        class: %mytrip_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
